### ISSUE TITLE
Remove hashes from package deps

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk/bem-graph#1]
- [x] ho-iter
- [x] bem-entity-name

**Comment by zxqfox** [comment]
@blond Waiting for release 0.3.0 of ho-iter. [bem-graph v0.0.1](https://www.npmjs.com/package/bem-graph) already in production.
![image](https://cloud.githubusercontent.com/assets/677518/17637572/1844bd6e-60ed-11e6-95c7-dfda925287b7.png)
